### ISSUE TITLE
support nest join

### ISSUE THREAD

**Issue by ni-ze** [apache/rocketmq-streams#199]
modify code for support nest join in rsqldb

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `enhancement` | Status: **Evaluated**

This proposes adding nested join support in RSQldb.

**Feasibility:** Nested join support is a reasonable SQL enhancement for the streams processing engine.

**Note:** If you have implementation code, please submit it as a pull request.

**Age:** This issue is from August 2022.

---
*Automated evaluation by RockteMQ-AI*
