### ISSUE TITLE
The demo runs failed when using JDK11

### ISSUE THREAD

**Issue by MatrixHB** [apache/rocketmq-streams#202]
I run the demo `RocketmqSourceExample1` failed with the following exception stack. 
![image](https://user-images.githubusercontent.com/23614576/187587180-350b5e0a-c1c4-4ef6-864f-559c08ee89c6.png)

After changing JDK 11 to JDK 8, problem solved. I think it's better to adapt the higher JDK version.

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `bug` | Status: **Evaluated**

The demo `RocketmqSourceExample1` fails with JDK 11 but works with JDK 8.

**Analysis:** This is a JDK compatibility issue. The codebase likely uses APIs or dependencies that behave differently between JDK 8 and 11.

**Recommendation:** The project should be tested and adapted for JDK 11+ compatibility. Common issues include:
- Removed/changed APIs between JDK 8 and 11
- Module system restrictions
- Dependency compatibility

**Age:** This issue is from August 2022. Please confirm if this is still an issue with the latest version and JDK 11+.

---
*Automated evaluation by RockteMQ-AI*
