### ISSUE TITLE
Use thread name as rocksdb path 

### ISSUE THREAD

**Issue by ni-ze** [apache/rocketmq-streams#257]
1. use the name of thread as rocksdb path;
2. clean the temporary data of rocksdb in local;
3. make WorkerThread shutdown method idempotent;

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `enhancement` | Status: **Valid (Stale)**

Enhancement to use thread names as RocksDB paths, clean up temporary RocksDB data on shutdown, and make `WorkerThread.shutdown()` idempotent. These are solid improvements for operational stability.

Open since January 2023. PR #256 was filed to implement this — please check if it was merged or if the changes need to be revisited against the current codebase.

---
*Automated evaluation by RockteMQ-AI*
