### ISSUE TITLE
Modify the configure of ObjectMapper

### ISSUE THREAD

**Issue by ni-ze** [apache/rocketmq-streams#261]

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `enhancement` | Status: **Needs Info**

This issue title suggests modifying the `ObjectMapper` configuration, but the issue body is empty.

**To proceed, please provide:**
- [ ] What specific `ObjectMapper` configuration change is needed?
- [ ] What problem does the current configuration cause?
- [ ] What version/commit is affected?

**Note:** This issue was opened in January 2023 (~3 years ago) with no description. If the issue is no longer relevant, maintainers may close it.

---
*Automated evaluation by github-manager*
