### ISSUE TITLE
The idle window does not trigger

### ISSUE THREAD

**Issue by ni-ze** [apache/rocketmq-streams#263]
1. Solve the idle window does not trigger;
2. Stop the rocketmqStream when process exit.

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `bug` | Status: **Needs Info**

This issue mentions two items:
1. Idle window does not trigger
2. Stop the rocketmqStream when process exits

The description is very terse and does not include enough detail to verify or reproduce the problem.

**To proceed with investigation, please provide:**
- [ ] What is the "idle window" feature and how is it configured?
- [ ] What behavior is expected vs observed when the idle window should trigger?
- [ ] What version/commit of rocketmq-streams is affected?
- [ ] Steps to reproduce the issue

**Note:** This issue was opened in January 2023 (~3 years ago). If the issue is no longer relevant, maintainers may close it.

---
*Automated evaluation by github-manager*
