### ISSUE TITLE
store watermark

### ISSUE THREAD

**Issue by ni-ze** [apache/rocketmq-streams#265]
store watermark and recover in streams instance restart or state migrate

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `enhancement` | Status: **Valid (Stale)**

Feature request to persist watermark state so it survives instance restarts or state migration. This is important for exactly-once semantics in stream processing.

Open since February 2023. Note that PR #264 was filed to address this — please check if it was merged or if the implementation needs to be revisited.

---
*Automated evaluation by RockteMQ-AI*
