### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by Jerryunclock** [apache/rocketmq-streams#278]
C:\Users\admin\AppData\Local\Temp\librocksdbjni2249986082963324944.dll: %1 不是有效的 Win32 应用程序

**Comment by ni-ze** [comment]
@justinmclean 你好，请问需要怎么复现你的报错？

**Comment by Jerryunclock** [comment]
已经找到问题了,电脑缺少了 vc++ 2015-2018 的运行环境,导致 rocksdb的 dll 文件无法加载

Ni Ze ***@***.***> 于2023年3月13日周一 10:06写道：

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `question`

The `UnsatisfiedLinkError` for `librocksdbjni` on Windows is a native library loading issue. This typically occurs because:

1. **Architecture mismatch**: Ensure your JDK architecture (x86_64/aarch64) matches the RocksDB JNI native library bundled with your RocketMQ Streams version.

2. **Missing Visual C++ Redistributable**: RocksDB JNI on Windows requires the Microsoft Visual C++ Redistributable runtime. Install the latest [VC++ Redistributable](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist) if not already present.

3. **RocksDB JNI version**: Check that the `rocksdbjni` dependency version in your classpath includes Windows native binaries. Newer versions generally have better Windows support.

4. **Workaround**: If you don't need local state storage, you can try running without RocksDB by using a different state backend, or run in a Linux environment (WSL2/Docker).

If the issue persists after checking the above, please share:
- Your exact JDK version and architecture (`java -version`)
- Your OS version and architecture
- The full stack trace as text

---
*Automated evaluation by RocketMQ AI Assistant*
